server:
  port: 8002

spring:
  application:
    name: mango-backup
  boot:
    admin:
      client:
        url: http://localhost:8000
  datasource:
    url: jdbc:mysql://localhost:3306/mango?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoints:
    web:
      exposure:
        include: "*"

mango:
  backup:
    datasource:
      host: localhost
      userName: root
      password: root
      database: mango
      port: 3306

